spring:
  cloud:
    kubernetes:
      loadbalancer:
        mode: service
    gateway:
      routes:
        - id: gateway-service
          uri: lb://gateway-service
          predicates:
            - Path=/actuator/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/v1/orders/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/v1/tasks/**
          filters:
            - SaveSession
        - id: frontend
          uri: lb://frontend-service
          predicates:
            - Path=/home,/taskPage
          filters:
            - SaveSession
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8080"
              - "http://localhost"
            allowedHeaders: "*"
            allowedMethods: "*"
            allowCredentials: true
