version: '3.2'
services:
  consul:
    image: consul:latest
    container_name: consul
    ports:
      - "8500:8500"
    command: "agent -server -bootstrap -ui -client=0.0.0.0"

  gateway-service:
    image: gateway-service:0.0.1-SNAPSHOT
    container_name: gateway-service
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=consul
      - CONSUL_HOST=consul
      - SPRING_REDIS_HOST=redis
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - OKTA_CLIENT_ID=${OKTA_CLIENT_ID}
      - OKTA_CLIENT_SECRET=${OKTA_CLIENT_SECRET}
      - OKTA_DOMAIN=${OKTA_DOMAIN}
      - FRONTEND_URL=lb://frontend-service
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - order-service
      - task-service
      - frontend-service
      - redis

  order-service:
    image: order-webmvc-service:0.0.1-SNAPSHOT
    container_name: order-service
    environment:
      - SERVER_PORT=8081
      - SPRING_PROFILES_ACTIVE=consul
      - OKTA_DOMAIN=${OKTA_DOMAIN}
      - CONSUL_HOST=consul
    expose:
      - "8081"
    ports:
      - "8081:8081"

  frontend-service:
    image: frontend-service:0.0.1-SNAPSHOT
    container_name: frontend-service
    environment:
      - SERVER_PORT=8082
      - SPRING_PROFILES_ACTIVE=consul
      - CONSUL_HOST=consul
      - SPRING_REDIS_HOST=redis
      - ORDER_SERVICE_URL=http://order-service:8081
    depends_on:
      - redis
    expose:
      - "8082"
    ports:
      - "8082:8082"

  task-service:
    image: task-webflux-service:0.0.1-SNAPSHOT
    container_name: task-service
    environment:
      - SERVER_PORT=8083
      - SPRING_PROFILES_ACTIVE=consul
      - CONSUL_HOST=consul
      - SPRING_REDIS_HOST=redis
    depends_on:
      - redis
    expose:
      - "8083"
    ports:
      - "8083:8083"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"